admin_header_title = \uAD00\uB9AC\uC790 \uD398\uC774\uC9C0
admin_header_movie = \uC601\uD654
admin_header_user = \uD68C\uC6D0
admin_header_review = \uB9AC\uBDF0
admin_header_membership = \uBA64\uBC84\uC2ED
admin_header_korean = \uD55C\uAD6D\uC5B4
admin_header_english = \uC601\uC5B4

admin_update = \uC218\uC815
admin_delete = \uC0AD\uC81C

admin_movies_main = \uC601\uD654 \uBAA9\uB85D
admin_movies_add = \uC601\uD654 \uCD94\uAC00
admin_movies_edit = \uC601\uD654 \uC218\uC815
admin_movies_movieId = \uC601\uD654 ID
admin_movies_title = \uC601\uD654 \uC81C\uBAA9
admin_movies_content = \uC601\uD654 \uC124\uBA85
admin_movies_price = \uAC00\uACA9
admin_movies_score = \uD3C9\uC810
admin_movies_image = \uC601\uD654 \uC774\uBBF8\uC9C0
admin_movies_release_date = \uAC1C\uBD09\uC77C
admin_movies_link = \uC601\uC0C1 \uB9C1\uD06C

admin_users_main = \uC0AC\uC6A9\uC790 \uBAA9\uB85D
admin_users_add = \uC0AC\uC6A9\uC790 \uCD94\uAC00
admin_users_edit = \uC0AC\uC6A9\uC790 \uC218\uC815
admin_users_userId = \uC0AC\uC6A9\uC790 ID
admin_users_email = \uC774\uBA54\uC77C
admin_users_password = \uBE44\uBC00\uBC88\uD638
admin_users_nickname = \uB2C9\uB124\uC784
admin_users_role = \uAD8C\uD55C
admin_users_cardnumber = \uCE74\uB4DC \uBC88\uD638

admin_membership_main = \uBA64\uBC84\uC2ED \uBAA9\uB85D
admin_membership_add = \uBA64\uBC84\uC2ED \uCD94\uAC00
admin_membership_edit = \uBA64\uBC84\uC2ED \uC218\uC815
admin_membership_membershipId = \uBA64\uBC84\uC2ED ID
admin_membership_name = \uBA64\uBC84\uC2ED \uC774\uB984
admin_membership_content = \uD61C\uD0DD \uB0B4\uC6A9
admin_membership_price = \uAC00\uACA9